### ISSUE TITLE
Реализовать хождение в github

### ISSUE THREAD

**Issue by just-boris** [just-boris/o-board#1]
Сделать js-хелпер, забирающий из github нужные данные и агрегирующий их в наше представляение

**Comment by tormozz48** [comment]
Как я понимаю речь идет чисто о клиенте?

**Comment by tormozz48** [comment]
Я бы хотел поучаствовать в обсуждении

**Comment by just-boris** [comment]
Да. Чисто на клиенте враппер. На него можно будет написать unit-тесты и замокать. Тогда не получится так, что github тебя забанит за число запросов пока ты будешь разрабатывать

**Comment by qfox** [comment]
Разве не готово?

**Comment by just-boris** [comment]
Ok
