### ISSUE TITLE
Создать блок app с логикой переключения страниц

### ISSUE THREAD

**Issue by tormozz48** [just-boris/o-board#10]
Необходимо создать блок app, в котором будет реализована логика переключения состояния страницы между 2 состояниями:
1. Выбор организаций для аггрегации issues с репозиториев этих организаций
2. Собственно главная страница приложения

**Comment by just-boris** [comment]
я взял блок из другого приложения, он там назывался skeleton. Можете и переименовать

**Comment by just-boris** [comment]
Вроде блок app удался.
